#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_ortho_5x12(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_EQL, KC_GRV, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_MINS, KC_QUOT, LGUI_T(KC_A), LALT_T(KC_S), LSFT_T(KC_D), LCTL_T(KC_F), KC_G, KC_H, RCTL_T(KC_J), RSFT_T(KC_K), RALT_T(KC_L), RGUI_T(KC_SCLN), KC_LBRC, KC_BSLS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_RBRC, KC_NO, KC_NO, KC_NO, KC_NO, LT(1,KC_SPC), LT(1,KC_SPC), LT(1,KC_BSPC), LT(1,KC_BSPC), KC_NO, KC_NO, KC_NO, KC_NO),
    [1] = LAYOUT_ortho_5x12(KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_NO, KC_NO, KC_INS, KC_PGUP, KC_DEL, KC_NO, KC_NO, KC_NO, KC_UP, KC_NO, KC_NO, KC_NO, KC_CAPS, LGUI_T(KC_NO), LALT_T(KC_HOME), LSFT_T(KC_PGDN), LCTL_T(KC_END), KC_NO, KC_NO, RCTL_T(KC_LEFT), RSFT_T(KC_DOWN), RALT_T(KC_RGHT), RGUI_T(KC_NO), KC_NO, KC_NO, KC_NO, KC_MUTE, KC_VOLD, KC_VOLU, KC_NO, KC_NO, KC_PSCR, KC_SCRL, KC_PAUS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_TAB, KC_ENT, KC_ENT, KC_NO, KC_NO, KC_NO, KC_NO)
};

void keyboard_post_init_user(void) {
#ifdef RGB_MATRIX_ENABLE
    rgb_matrix_set_speed_noeeprom(64);
    rgb_matrix_mode_noeeprom(RGB_MATRIX_HUE_BREATHING);
    rgb_matrix_sethsv_noeeprom(HSV_RED);
    rgb_matrix_set_flags_noeeprom(2+4);
#endif // RGB_MATRIX_ENABLE
}
